# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Base"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V21"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V22"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V22_ZSegments"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V23"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V231"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V24"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V25"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V251"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V26"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V271"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V28"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/NHapi.Model.V281"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget" 
    directory: "/src/ModelGenerator" 
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/NHapi.SourceGeneration"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.Base.NUnit"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.NUnit"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.NUnit.SourceGeneration"
    schedule:
      interval: "daily"
