name: Publish Code Coverage Results

on:
  workflow_run:
    workflows: ["Receive Pull Request"]
    types:
      - completed

jobs:
  publish-test-results:
    name: Publish Code Coverage Results
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      ( github.event.workflow_run.conclusion == 'success'  ||
      github.event.workflow_run.conclusion == 'failure' ) }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "coverage-reports"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/coverage-reports.zip', Buffer.from(download.data));
      - run: |
          unzip coverage-reports.zip
          rm coverage-reports.zip
      
      - run: echo ${{ github.event.workflow_run }}

      - name: Publish Code Coverage Results
        uses: codecov/codecov-action@v1
        with:
          files: "**/Cobertura.xml"
          override_commit: ${{ github.event.workflow_run.head_sha }}

      - name: Publish Code Coverage Results
        uses: 5monkeys/cobertura-action@master
        with:
          path: "**/Cobertura.xml"